name: CheckIfCovid US

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Codecov
      uses: codecov/codecov-action@v1.0.6
    - run: npm install
    - run: npm run build --if-present
    - run: pm2 reload default
