name: CheckIfCovid US

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: pm2 reload checkifcovid-us --update-env
      env:
        CI: true
        SLACK_HOOK: ${{ secrets.SLACK_HOOK }}
